name: Pictures Test
favicon: null
layout_spectrum: 0.38879
typography_spectrum: 0.86459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040511'
    - '#4c2d49'
    - '#a4606e'
    - '#d8caee'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
