name: Pictures Test
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86459
title: 'Fireworks!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040511'
    - '#4c2d49'
    - '#a4606e'
    - '#d8caee'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
